config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :events
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :enrollments, only: [:create, :destroy, :update]

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  enum status: { invited: 0, accepted: 1 }
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :enrollments
  has_many :attendees, through: :enrollments, source: :user
  scope :past, -> { where('start_date < ?', Date.today) }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, inverse_of: :creator
  has_many :enrollments
  has_many :attended_events, through: :enrollments, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index; end

  private

  def require_login
    redirect_to login_path, alert: 'Sign up or Log in to see the events!' unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :require_login

  def create
    event = Event.find(params[:event_id])
    enrollment = Enrollment.new(event_id: event.id, user_id: params[:user_id])

    if enrollment.save
      enrollment.invited!
      flash[:notice] = 'Invitation sent!'
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Ooops! Something went wrong...'
      redirect_to event_path(event)
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    enrollment = Enrollment.find(params[:id])
    if current_user == event.creator
      enrollment.destroy
      flash[:notice] = 'The invitation is cancelled!'
    else
      enrollment.invited!
      # enrollment.save
      flash[:notice] = "You have dropped the enrollment for the #{event.name}!"
    end

    redirect_to users_path(event_id: event.id, id: enrollment.id)
  end

  def update
    @event = Event.find(params[:event_id])
    @enrollment = Enrollment.find_by(event_id: params[:event_id], user_id: current_user.id)
    if @enrollment&.invited?
      @enrollment.accepted!
      flash[:notice] = "Thank you for signing up for the '#{@event.name}'!"
    else
      flash[:alert] = 'Your name is not on the invitation list'
    end

    redirect_to event_path(@event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :require_login, except: [:index, :show]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Event '#{@event.name}' created!"
      redirect_to @event
    else
      flash[:alert] = 'Some error!'
      render 'new'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
	def sign_up_params
	  params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end
  
	def account_update_params
	  params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_name(params[:name])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Name is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :require_login, except: %i[new create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    session[:user_id] = @user.id
    flash.notice = "User #{@user.name} successfully created! Thank you for signing up!"
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:name, :start_date, :location, :description, :user_id)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

app/views/enrollments/destroy.html.erb
<h1>Enrollments#destroy</h1>
<p>Find me in app/views/enrollments/destroy.html.erb</p>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.label :name, class: "label" %>
      <%= f.text_field :name, class: "input", autofocus: true %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :start_date, class: "label" %>
      <%= f.date_select :start_date, type: "date", class: "input" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :location, class: "label" %>
      <%= f.text_field :location, class: "input" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :description, class: "label" %>
      <%= f.text_field :description, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit "Create Event", class:"button is-primary is-large is-fullwidth" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= link_to 'Cancel', root_path, class:"button is-large is-fullwidth" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="top">
  <div class="section">
    <h2 class="title is-2">Upcoming Events</h2>
    <div class="columns">
      <% @events.upcoming.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= link_to event.name, event_path(event), class: "card-header-title is-centered" %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event.description.truncate_words(12) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item is-narrow"><%= event.start_date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="bottom">
  <div class="section">
    <h2 class="title is-2">Past Events</h2>
    <div class="columns">
      <% @events.past.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= link_to event.name, event_path(event), class: "card-header-title is-centered" %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event.description.truncate_words(12) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item"><%= event.start_date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="section">
  <div class="container">
	<div class="columns is-centered">
	  <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Create Event</h2>
        <%= render 'form', event: @event %>
        <%= link_to 'Back', events_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="box">
          <h2 class="title is-2 is-spaced has-text-centered mb-6"><%= @event.name %></h2>

          <div class="columns is-mobile is-centered">
            <div class="column is-5">
              <p><small>Hosted by</small></p>
              <h4 class="subtitle is-4"><%= @event.creator.name %></h4>
            </div>
          
            <div class="column">
              <div class="dropdown is-hoverable">
                <div class="dropdown-trigger">
                  <button class="button is-fullwidth" aria-haspopup="true" aria-controls="dropdown-menu3">
                    <span>Invitees: <%= User.find(@event.enrollments.invited.map { |enr| enr.user_id }).count %></span>
                  </button>
                </div>
                <div class="dropdown-menu" id="dropdown-menu6" role="menu">
                  <div class="dropdown-content">
                    <ul>
                      <% if User.find(@event.enrollments.invited.map { |enr| enr.user_id }).any? %>
                        <div class="dropdown-item">
                          <% User.find(@event.enrollments.invited.map { |enr| enr.user_id }).each do |user| %>
                            <li><p><%= user.name %></p></li>
                          <% end %>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div class="column">
              <div class="dropdown is-hoverable">
                <div class="dropdown-trigger">
                  <button class="button is-fullwidth" aria-haspopup="true" aria-controls="dropdown-menu3">
                    <span>Attendies: <%= User.find(@event.enrollments.accepted.map { |enr| enr.user_id }).count %></span>
                  </button>
                </div>
                <div class="dropdown-menu" id="dropdown-menu6" role="menu">
                  <div class="dropdown-content">
                    <ul>
                      <% if User.find(@event.enrollments.accepted.map { |enr| enr.user_id }).any? %>
                        <div class="dropdown-item">
                          <% User.find(@event.enrollments.accepted.map { |enr| enr.user_id }).each do |user| %>
                            <li><p><%= user.name %></p></li>
                          <% end %>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <p class="has-text-justified"><%= @event.description %></p><br/>

          <div class="columns is-mobile is-centered">
            <div class="column">
              <div class="card">
                <div class="card-header">
                  <p class="card-header-title is-centered"><%= @event.location %></p>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="card">
                <div class="card-header">
                  <p class="card-header-title is-centered"><%= @event.start_date %></p>
                </div>
              </div>
            </div>
          </div>

          <br/>

          <% if @event.creator == current_user %>
            <%= button_to "Invite", users_path, params: {:event_id => @event.id}, method: :get, class: "button is-info is-large is-fullwidth" %>
          <% else %>
            <% enrollment = Enrollment.find_by(event_id: @event.id, user_id: current_user.id) %>
            <% if enrollment && enrollment.accepted? %>
              <%= button_to "Cancel enrollment", enrollment_path(id: enrollment.id, event_id: @event.id, user_id: current_user.id), method: :delete, class: "button is-danger is-large is-fullwidth" %>
            <% else %>
              <%= button_to "Enroll", enrollment_path(event_id: @event.id), method: :patch, class: "button is-primary is-large is-fullwidth" %>
            <% end %>
          <% end %>

          <br/>
          <%= link_to 'Edit', edit_event_path(@event) %> |
          <%= link_to 'Back', events_path %>

          <%= link_to 'Back to Event List', root_path, class: "button is-fullwidth" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <div class="navbar-item">
            <img src="https://clipartstation.com/wp-content/uploads/2017/11/clipart-binatang-7.jpg" width="25" height="25">
          </div>
          <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-4">Private Event</h1>
          <% end %>

          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "Create event", new_event_path, class: "button is-white" %>
                </p>
                <% if current_user %>
                  <p class="control">
                    <%= link_to current_user.name, user_path(current_user), class: "button is-white" %>
                  </p>
                  <p>
                    <%= link_to "Logout", logout_path, class: "button is-white" %>
                  </p>
                <% else %>
                  <p class="control">
                    <%= link_to 'Sign In', login_path, class: "button is-white" %>
                  </p>
                  <p class="control">
                    <%= link_to 'Sign Up', signup_path, class: "button is-white" %>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f|%>
  <div class="field">
    <div class="control">
      <%= f.label :name, class: "label"%>
      <%= f.text_field :name, class: "input", autofocus: true%>
    </div>
  </div>

  <div class="field">
    <div class="control">
     <%= f.submit "Sign Up", class: "button is-primary is-large is-fullwidth"%>
    </div>
  </div>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="box">
          <h2 class="title is-2 is-spaced has-text-centered mb-6">Guest List</h2>
    
          <div class="columns is-centered">
            <table class="table is-fullwidth is-hoverable">
              <tbody>
                <th class="has-text-centered">Name</th>
                <th class="has-text-centered">Status</th>
                <th class="has-text-centered">Action</th>
                <% @users.reject { |user| user == Event.find(params[:event_id]).creator }.each do |user| %>
                  <% enrollment = Enrollment.find_by(event_id: params[:event_id], user_id: user.id) %>
                  <tr>
                    <td class="has-text-centered">
                      <%= user.name %>
                    </td>
                    <% unless enrollment.nil? || enrollment.status.nil? %>
                      <td class="has-text-centered">
                        <span class="tag is-primary is-medium is-light"><%= enrollment.status %><span>
                      </td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <% if enrollment.nil? %>
                      <td class="has-text-centered">
                        <%= button_to "Invite", enrollments_path(event_id: params[:event_id], user_id: user.id), class: "button is-primary is-small" %>
                      </td>
                    <% else %>
                      <td class="has-text-centered">
                        <%= button_to "Cancel Invitation", enrollment_path(id: enrollment.id, event_id: params[:event_id]), method: :delete, class: "button is-danger is-small" %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <br/>

          <%= link_to 'Back to Event Details', event_path(id: params[:event_id]), class: "button is-fullwidth" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class= "section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
       <h1 class="title is-5">Sign Up</h1>
        <%= render 'form', user: @user%>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
	  <div class="columns is-centered">
      <div class="column is-9">
        <h2 class="title is-2 is-spaced has-text-centered"><%= @user.name %>'s Profile</h2>
	      <div class="columns is-centered">
          <div class="column has-text-centered">
            <h3 class="subtitle is-3 has-text-centered">Hosted Events: <%= @user.events.count %></h3>
            <ul>
              <% if @user.events.empty? %>
                <p>User is not hosting</p>
              <% else %>
                <% @user.events.each do |event| %>
                  <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>

          <div class="column has-text-centered">
            <h3 class="subtitle is-3">Upcoming Events: <%= @user.attended_events.where('start_date >= ?', Date.today).count %></h3>
            <ul>
              <% if @user.attended_events.where('start_date >= ?', Date.today).count.zero? %>
                <p>No planned parties</p>
              <% else %>
                <% @user.attended_events.where('start_date >= ?', Date.today).each do |event| %>
                  <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>

          <div class="column has-text-centered">
            <h3 class="subtitle is-3 has-text-centered">Attended Events: <%= @user.attended_events.where('start_date < ?', Date.today).count %></h3>
            <ul>
              <% if @user.attended_events.empty? %>
                <p>User is not partying</p>
              <% else %>
                <% @user.attended_events.where('start_date < ?', Date.today).each do |event| %>
                  <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>